- name: copy prod check-oc.py to /usr/local/bin/
  template:
    src: check-oc.py
    dest: /usr/local/bin/check-oc.py
    owner: root
    group: root
    mode: 0755

- name: create crontab for the task
  cron: 
    name: "check_openshift_state"
    job: "/usr/local/bin/check-oc.py"
    hour: "8-17"
    minute: "55"
    day: "*"
    month: "*"
    weekday: "*"


